### ISSUE TITLE
AttributeError: 'LSTM' object has no attribute '_flat_weights'

### ISSUE THREAD

**Issue by Tobulo** [ahoarfrost/fastBio#4]
Hey, I am trying to follow the tutorial on my PC (with GPU) and I have encountered this error below when I try to load the trained models (as described at the end of the tutorial):

>>> from fastai.text import load_learner
>>> oxido = load_learner(Path('./models').resolve(), 'OxidoreductaseClassifier_export.pkl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/novo01/anaconda3/envs/myenv/lib/python3.9/site-packages/fastai/basic_train.py", line 598, in load_learner
    state = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/home/novo01/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/novo01/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/serialization.py", line 1272, in _legacy_load
    result = unpickler.load()
  File "/home/novo01/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 353, in __setstate__
    for w in self._flat_weights]
  File "/home/novo01/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LSTM' object has no attribute '_flat_weights'
<img width="1067" alt="error" src="https://github.com/ahoarfrost/fastBio/assets/28929377/2a7aeed2-2eb0-4cac-a717-f93c4c842ef2">

I am using conda env with python3.9, numpy-1.23.0 and pandas-1.3.5, the fastai-1.0.52 as default. I new to the machine learning and have little background of programming, would you please help me understand the issue and what should I do to correct the error?

P.S. after checking with the requirements, I found that only torch and torchvision have different version, but I tried to install older version of torch on my PC, it seems not compatible with the system. Is the error related to this?

<img width="1658" alt="torch" src="https://github.com/ahoarfrost/fastBio/assets/28929377/4b5ad033-259d-447e-8a2f-f3e9889e8974">
<img width="1658" alt="torch_1" src="https://github.com/ahoarfrost/fastBio/assets/28929377/701b4c0b-504f-4cde-bf17-8490976cca5f">

Thank you very much!

Best,
Toby

**Comment by Tobulo** [comment]
okay, so I created another env with python3.6, and now I can install correct version of torch, and is seems to be working now!

**Comment by ahoarfrost** [comment]
great! Yes fastai v1 is no longer supported so you'll have to use the (very old) version dependencies in the requirements.txt to get the existing tutorials to work.
